#!/usr/bin/env bash

set -Eeuo pipefail

: "${K8S_SEALOS_CONTEXT_DIR:?K8S_SEALOS_CONTEXT_DIR is required}"
: "${K8S_SEALOS_COMMON_DIR:?K8S_SEALOS_COMMON_DIR is required}"

SCRIPT_DIR="${K8S_SEALOS_CONTEXT_DIR}"
COMMON_DIR="${K8S_SEALOS_COMMON_DIR}"
VERSIONS_FILE="${SCRIPT_DIR}/versions.env"
INSTALL_SCRIPT="${SCRIPT_DIR}/install.sh"
INSTALL_COMMON_FILE="${COMMON_DIR}/install-common.sh"
BIN_DIR="${SCRIPT_DIR}/bin"
IMAGES_DIR="${SCRIPT_DIR}/images"
BUILD_DIR="${SCRIPT_DIR}/.build"
DIST_DIR="${SCRIPT_DIR}/dist"
PAYLOAD_DIR="${BUILD_DIR}/payload"
PAYLOAD_TAR="${BUILD_DIR}/payload.tar.gz"
PAYLOAD_LIB_DIR="${PAYLOAD_DIR}/lib"
PAYLOAD_VERSIONS_FILE="${BUILD_DIR}/payload-versions.env"
IMAGE_JSON="${IMAGES_DIR}/image.json"
IMAGE_MAPPING="${IMAGES_DIR}/image-mapping.txt"
MANIFEST_FILE="${BUILD_DIR}/release-manifest.env"

DOWNLOAD_BINARIES="true"
PREPARE_IMAGES="true"
FORCE="false"
CLEAN_ONLY="false"

RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() {
  echo -e "${CYAN}[INFO]${NC} $*"
}

warn() {
  echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

die() {
  echo -e "${RED}[ERROR]${NC} $*" >&2
  exit 1
}

usage() {
  cat <<EOF
用法:
  $(basename "$0") [选项]

选项:
  --skip-binary-download   不下载官方 Sealos 二进制，直接使用当前 bin 目录
  --skip-image-prepare     不拉取/打包镜像，仅刷新镜像清单并生成 .run
  --force                  强制重新下载二进制并重新打包镜像
  --clean                  仅清理构建产物后退出
  -h, --help               显示帮助

说明:
  1. 组件版本统一从 ../common/component-versions.env 维护
  2. 架构差异只保留在当前目录的 versions.env
  3. 默认输出 dist/\${INSTALLER_NAME}
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --skip-binary-download)
        DOWNLOAD_BINARIES="false"
        shift
        ;;
      --skip-image-prepare)
        PREPARE_IMAGES="false"
        shift
        ;;
      --force)
        FORCE="true"
        shift
        ;;
      --clean)
        CLEAN_ONLY="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "未知参数: $1"
        ;;
    esac
  done
}

load_versions() {
  [[ -f "${VERSIONS_FILE}" ]] || die "缺少版本文件: ${VERSIONS_FILE}"
  [[ -f "${INSTALL_SCRIPT}" ]] || die "缺少安装脚本: ${INSTALL_SCRIPT}"
  [[ -f "${INSTALL_COMMON_FILE}" ]] || die "缺少公共安装脚本: ${INSTALL_COMMON_FILE}"

  # shellcheck disable=SC1090
  source "${VERSIONS_FILE}"

  : "${ARCH:?ARCH is required}"
  : "${PLATFORM:?PLATFORM is required}"
  : "${SEALOS_VERSION:?SEALOS_VERSION is required}"
  : "${IMAGE_REGISTRY:?IMAGE_REGISTRY is required}"
  : "${K8S_IMAGE_NAME:?K8S_IMAGE_NAME is required}"
  : "${K8S_VERSION:?K8S_VERSION is required}"
  : "${HELM_IMAGE_NAME:?HELM_IMAGE_NAME is required}"
  : "${HELM_VERSION:?HELM_VERSION is required}"
  : "${CNI_IMAGE_NAME:?CNI_IMAGE_NAME is required}"
  : "${CNI_VERSION:?CNI_VERSION is required}"
  : "${K8S_IMAGE_TAR:?K8S_IMAGE_TAR is required}"
  : "${HELM_IMAGE_TAR:?HELM_IMAGE_TAR is required}"
  : "${CNI_IMAGE_TAR:?CNI_IMAGE_TAR is required}"

  INSTALLER_NAME="${INSTALLER_NAME:-k8s-sealos-linux-${ARCH}.run}"
  K8S_IMAGE="${IMAGE_REGISTRY}/${K8S_IMAGE_NAME}:${K8S_VERSION}"
  HELM_IMAGE="${IMAGE_REGISTRY}/${HELM_IMAGE_NAME}:${HELM_VERSION}"
  CNI_IMAGE="${IMAGE_REGISTRY}/${CNI_IMAGE_NAME}:${CNI_VERSION}"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"
}

ensure_requirements() {
  require_cmd curl
  require_cmd tar
  require_cmd sha256sum

  if [[ "${PREPARE_IMAGES}" == "true" ]]; then
    require_cmd docker
  fi
}

clean_artifacts() {
  rm -rf "${BUILD_DIR}"
  rm -f "${DIST_DIR}/${INSTALLER_NAME}" "${DIST_DIR}/${INSTALLER_NAME}.sha256"
}

prepare_directories() {
  mkdir -p "${BIN_DIR}" "${IMAGES_DIR}" "${BUILD_DIR}" "${DIST_DIR}" "${PAYLOAD_DIR}" "${PAYLOAD_LIB_DIR}"
}

write_image_manifest() {
  cat > "${IMAGE_JSON}" <<EOF
[
  {
    "pull": "${CNI_IMAGE}",
    "tag": "${CNI_IMAGE}",
    "tar": "${CNI_IMAGE_TAR}"
  },
  {
    "pull": "${HELM_IMAGE}",
    "tag": "${HELM_IMAGE}",
    "tar": "${HELM_IMAGE_TAR}"
  },
  {
    "pull": "${K8S_IMAGE}",
    "tag": "${K8S_IMAGE}",
    "tar": "${K8S_IMAGE_TAR}"
  }
]
EOF

  cat > "${IMAGE_MAPPING}" <<EOF
# Generated by $(basename "$0")
${CNI_IMAGE} -> ${CNI_IMAGE_TAR}
${HELM_IMAGE} -> ${HELM_IMAGE_TAR}
${K8S_IMAGE} -> ${K8S_IMAGE_TAR}
EOF
}

download_sealos_binaries() {
  local bundle_url
  local bundle_file

  bundle_url="https://github.com/labring/sealos/releases/download/${SEALOS_VERSION}/sealos_${SEALOS_VERSION#v}_linux_${ARCH}.tar.gz"
  bundle_file="${BUILD_DIR}/sealos_${SEALOS_VERSION#v}_linux_${ARCH}.tar.gz"

  if [[ "${FORCE}" == "false" ]] \
    && [[ -x "${BIN_DIR}/sealos" ]] \
    && [[ -x "${BIN_DIR}/sealctl" ]] \
    && [[ -x "${BIN_DIR}/image-cri-shim" ]] \
    && [[ -x "${BIN_DIR}/lvscare" ]]; then
    log "bin 目录已存在 Sealos 二进制，跳过下载"
    return
  fi

  log "下载官方 Sealos 二进制: ${bundle_url}"
  curl -fL --retry 3 --retry-delay 2 -o "${bundle_file}" "${bundle_url}"

  rm -f "${BIN_DIR}/sealos" "${BIN_DIR}/sealctl" "${BIN_DIR}/image-cri-shim" "${BIN_DIR}/lvscare"
  tar -xzf "${bundle_file}" -C "${BIN_DIR}"
  chmod +x "${BIN_DIR}/sealos" "${BIN_DIR}/sealctl" "${BIN_DIR}/image-cri-shim" "${BIN_DIR}/lvscare"
}

prepare_images() {
  local entries=(
    "${CNI_IMAGE}|${CNI_IMAGE_TAR}"
    "${HELM_IMAGE}|${HELM_IMAGE_TAR}"
    "${K8S_IMAGE}|${K8S_IMAGE_TAR}"
  )
  local entry

  for entry in "${entries[@]}"; do
    IFS='|' read -r image_ref tar_name <<< "${entry}"
    local tar_path="${IMAGES_DIR}/${tar_name}"

    if [[ "${FORCE}" == "false" && -f "${tar_path}" ]]; then
      log "镜像包已存在，跳过: ${tar_name}"
      continue
    fi

    log "拉取镜像: ${image_ref}"
    docker pull --platform "${PLATFORM}" "${image_ref}"

    log "导出镜像: ${tar_path}"
    docker save -o "${tar_path}" "${image_ref}"
  done
}

write_release_manifest() {
  cat > "${MANIFEST_FILE}" <<EOF
ARCH="${ARCH}"
PLATFORM="${PLATFORM}"
INSTALLER_NAME="${INSTALLER_NAME}"
SEALOS_VERSION="${SEALOS_VERSION}"
IMAGE_REGISTRY="${IMAGE_REGISTRY}"
K8S_IMAGE_NAME="${K8S_IMAGE_NAME}"
K8S_VERSION="${K8S_VERSION}"
K8S_IMAGE_TAR="${K8S_IMAGE_TAR}"
HELM_IMAGE_NAME="${HELM_IMAGE_NAME}"
HELM_VERSION="${HELM_VERSION}"
HELM_IMAGE_TAR="${HELM_IMAGE_TAR}"
CNI_IMAGE_NAME="${CNI_IMAGE_NAME}"
CNI_VERSION="${CNI_VERSION}"
CNI_IMAGE_TAR="${CNI_IMAGE_TAR}"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF
}

write_payload_versions() {
  cat > "${PAYLOAD_VERSIONS_FILE}" <<EOF
SEALOS_VERSION="${SEALOS_VERSION}"
IMAGE_REGISTRY="${IMAGE_REGISTRY}"
K8S_IMAGE_NAME="${K8S_IMAGE_NAME}"
K8S_VERSION="${K8S_VERSION}"
K8S_IMAGE_TAR="${K8S_IMAGE_TAR}"
HELM_IMAGE_NAME="${HELM_IMAGE_NAME}"
HELM_VERSION="${HELM_VERSION}"
HELM_IMAGE_TAR="${HELM_IMAGE_TAR}"
CNI_IMAGE_NAME="${CNI_IMAGE_NAME}"
CNI_VERSION="${CNI_VERSION}"
CNI_IMAGE_TAR="${CNI_IMAGE_TAR}"
ARCH="${ARCH}"
PLATFORM="${PLATFORM}"
INSTALLER_NAME="${INSTALLER_NAME}"
EOF
}

stage_payload() {
  rm -rf "${PAYLOAD_DIR}"
  mkdir -p "${PAYLOAD_DIR}/bin" "${PAYLOAD_DIR}/images" "${PAYLOAD_LIB_DIR}"

  cp -f "${BIN_DIR}/sealos" "${PAYLOAD_DIR}/bin/"
  cp -f "${BIN_DIR}/sealctl" "${PAYLOAD_DIR}/bin/"
  cp -f "${BIN_DIR}/image-cri-shim" "${PAYLOAD_DIR}/bin/"
  cp -f "${BIN_DIR}/lvscare" "${PAYLOAD_DIR}/bin/"
  chmod +x "${PAYLOAD_DIR}/bin/"*

  cp -f "${IMAGE_JSON}" "${PAYLOAD_DIR}/images/"
  cp -f "${IMAGE_MAPPING}" "${PAYLOAD_DIR}/images/"
  cp -f "${PAYLOAD_VERSIONS_FILE}" "${PAYLOAD_DIR}/versions.env"
  cp -f "${MANIFEST_FILE}" "${PAYLOAD_DIR}/release-manifest.env"
  cp -f "${INSTALL_COMMON_FILE}" "${PAYLOAD_LIB_DIR}/install-common.sh"

  if compgen -G "${IMAGES_DIR}/*.tar" >/dev/null 2>&1; then
    cp -f "${IMAGES_DIR}/"*.tar "${PAYLOAD_DIR}/images/"
  fi
}

create_installer() {
  tar -C "${PAYLOAD_DIR}" -czf "${PAYLOAD_TAR}" .
  cat "${INSTALL_SCRIPT}" "${PAYLOAD_TAR}" > "${DIST_DIR}/${INSTALLER_NAME}"
  chmod +x "${DIST_DIR}/${INSTALLER_NAME}"
  sha256sum "${DIST_DIR}/${INSTALLER_NAME}" > "${DIST_DIR}/${INSTALLER_NAME}.sha256"
}

print_summary() {
  log "构建完成"
  echo "  架构:        ${ARCH}"
  echo "  Sealos:      ${SEALOS_VERSION}"
  echo "  Kubernetes:  ${K8S_IMAGE}"
  echo "  Helm:        ${HELM_IMAGE}"
  echo "  Cilium:      ${CNI_IMAGE}"
  echo "  安装包:      ${DIST_DIR}/${INSTALLER_NAME}"
  echo "  校验文件:    ${DIST_DIR}/${INSTALLER_NAME}.sha256"
}

k8s_sealos_build_main() {
  parse_args "$@"
  load_versions
  ensure_requirements

  if [[ "${CLEAN_ONLY}" == "true" ]]; then
    clean_artifacts
    log "已清理构建产物"
    exit 0
  fi

  clean_artifacts
  prepare_directories
  write_image_manifest

  if [[ "${DOWNLOAD_BINARIES}" == "true" ]]; then
    download_sealos_binaries
  fi

  if [[ "${PREPARE_IMAGES}" == "true" ]]; then
    prepare_images
  else
    warn "已跳过镜像打包，仅刷新镜像清单并复用现有 tar 文件"
  fi

  write_release_manifest
  write_payload_versions
  stage_payload
  create_installer
  print_summary
}
